name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@master
      - name: Setup MySQL 5.7
        run: sudo apt-get install libmysqlclient-dev
      - name: Set up Ruby 2.6.x
        uses: actions/setup-ruby@v1
        with:
          version: 2.6.x
      - name: Setup Gemfiles
        run: |
          gem install bundler
          bundle install --path vendor/bundle
      - name: rubocop
        run: bundle exec rubocop
      - name: rspec
        run: bundle exec rspec
